goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../clojure/browser/event.js", ['clojure.browser.event'], ['cljs.core', 'goog.events.EventTarget', 'goog.events.EventType', 'goog.events']);
goog.addDependency("../clojure/browser/net.js", ['clojure.browser.net'], ['goog.net.xpc.CfgFields', 'goog.net.XhrIo', 'goog.json', 'goog.Uri', 'cljs.core', 'goog.net.EventType', 'goog.net.xpc.CrossPageChannel', 'clojure.browser.event']);
goog.addDependency("../weasel/impls/websocket.js", ['weasel.impls.websocket'], ['cljs.core', 'clojure.browser.net', 'goog.net.WebSocket', 'clojure.browser.event']);
goog.addDependency("../cljs/reader.js", ['cljs.reader'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../weasel/repl.js", ['weasel.repl'], ['weasel.impls.websocket', 'cljs.core', 'clojure.browser.net', 'cljs.reader', 'clojure.browser.event']);
goog.addDependency("../om/dom.js", ['om.dom'], ['cljs.core']);
goog.addDependency("../defender_cljs/constants.js", ['defender_cljs.constants'], ['cljs.core']);
goog.addDependency("../defender_cljs/canvas/system.js", ['defender_cljs.canvas.system'], ['cljs.core']);
goog.addDependency("../defender_cljs/utils.js", ['defender_cljs.utils'], ['defender_cljs.constants', 'cljs.core']);
goog.addDependency("../defender_cljs/canvas/object.js", ['defender_cljs.canvas.object'], ['cljs.core']);
goog.addDependency("../defender_cljs/actor.js", ['defender_cljs.actor'], ['defender_cljs.constants', 'cljs.core', 'defender_cljs.canvas.object']);
goog.addDependency("../defender_cljs/canvas/scene.js", ['defender_cljs.canvas.scene'], ['cljs.core', 'defender_cljs.utils']);
goog.addDependency("../defender_cljs/collision.js", ['defender_cljs.collision'], ['cljs.core', 'defender_cljs.utils', 'defender_cljs.actor', 'defender_cljs.canvas.scene']);
goog.addDependency("../defender_cljs/events.js", ['defender_cljs.events'], ['defender_cljs.canvas.system', 'cljs.core', 'defender_cljs.collision', 'defender_cljs.utils', 'defender_cljs.canvas.scene']);
goog.addDependency("../defender_cljs/canvas/geometry.js", ['defender_cljs.canvas.geometry'], ['cljs.core', 'defender_cljs.canvas.object']);
goog.addDependency("../defender_cljs/actors/projectile.js", ['defender_cljs.actors.projectile'], ['defender_cljs.constants', 'defender_cljs.events', 'cljs.core', 'defender_cljs.utils', 'defender_cljs.canvas.geometry', 'defender_cljs.actor', 'defender_cljs.canvas.scene']);
goog.addDependency("../defender_cljs/canvas/sprite.js", ['defender_cljs.canvas.sprite'], ['cljs.core', 'defender_cljs.canvas.object', 'defender_cljs.utils']);
goog.addDependency("../defender_cljs/enemy.js", ['defender_cljs.enemy'], ['cljs.core', 'defender_cljs.utils', 'defender_cljs.actor']);
goog.addDependency("../defender_cljs/enemies/lander.js", ['defender_cljs.enemies.lander'], ['defender_cljs.canvas.sprite', 'defender_cljs.enemy', 'cljs.core', 'defender_cljs.actor']);
goog.addDependency("../defender_cljs/systems/scene_bounds.js", ['defender_cljs.systems.scene_bounds'], ['defender_cljs.constants', 'cljs.core', 'defender_cljs.utils', 'defender_cljs.actor', 'defender_cljs.canvas.scene']);
goog.addDependency("../defender_cljs/vector.js", ['defender_cljs.vector'], ['cljs.core', 'defender_cljs.utils']);
goog.addDependency("../defender_cljs/physics.js", ['defender_cljs.physics'], ['defender_cljs.canvas.system', 'defender_cljs.vector', 'cljs.core', 'defender_cljs.utils', 'defender_cljs.actor']);
goog.addDependency("../defender_cljs/actors/ship.js", ['defender_cljs.actors.ship'], ['defender_cljs.canvas.sprite', 'defender_cljs.constants', 'defender_cljs.actors.projectile', 'defender_cljs.canvas.system', 'defender_cljs.events', 'cljs.core', 'defender_cljs.canvas.object', 'defender_cljs.utils', 'defender_cljs.actor', 'defender_cljs.physics']);
goog.addDependency("../defender_cljs/canvas/camera.js", ['defender_cljs.canvas.camera'], ['defender_cljs.constants', 'defender_cljs.canvas.system', 'cljs.core', 'defender_cljs.utils', 'defender_cljs.actor', 'defender_cljs.physics', 'defender_cljs.actors.ship']);
goog.addDependency("../defender_cljs/systems/scene_tracking.js", ['defender_cljs.systems.scene_tracking'], ['defender_cljs.constants', 'defender_cljs.canvas.system', 'cljs.core', 'defender_cljs.utils', 'defender_cljs.actor', 'defender_cljs.canvas.scene', 'defender_cljs.canvas.camera']);
goog.addDependency("../defender_cljs/canvas/text.js", ['defender_cljs.canvas.text'], ['cljs.core']);
goog.addDependency("../defender_cljs/canvas/hud.js", ['defender_cljs.canvas.hud'], ['defender_cljs.constants', 'cljs.core']);
goog.addDependency("../defender_cljs/overlay/core.js", ['defender_cljs.overlay.core'], ['defender_cljs.constants', 'defender_cljs.canvas.text', 'cljs.core', 'defender_cljs.canvas.object', 'defender_cljs.canvas.geometry', 'defender_cljs.canvas.hud']);
goog.addDependency("../clojure/set.js", ['clojure.set'], ['cljs.core']);
goog.addDependency("../defender_cljs/overlay/map.js", ['defender_cljs.overlay.map'], ['defender_cljs.constants', 'defender_cljs.canvas.system', 'cljs.core', 'clojure.set', 'defender_cljs.overlay.core', 'defender_cljs.canvas.object', 'defender_cljs.utils', 'defender_cljs.canvas.geometry', 'defender_cljs.actor', 'defender_cljs.canvas.scene', 'defender_cljs.canvas.camera']);
goog.addDependency("../defender_cljs/canvas/core.js", ['defender_cljs.canvas.core'], ['defender_cljs.constants', 'defender_cljs.actors.projectile', 'defender_cljs.canvas.system', 'defender_cljs.events', 'cljs.core', 'defender_cljs.enemies.lander', 'defender_cljs.systems.scene_bounds', 'defender_cljs.systems.scene_tracking', 'defender_cljs.overlay.core', 'defender_cljs.utils', 'defender_cljs.overlay.map', 'defender_cljs.actor', 'defender_cljs.physics', 'defender_cljs.canvas.scene', 'defender_cljs.actors.ship', 'defender_cljs.canvas.camera']);
goog.addDependency("../om/core.js", ['om.core'], ['cljs.core', 'om.dom', 'goog.ui.IdGenerator']);
goog.addDependency("../defender_cljs/core.js", ['defender_cljs.core'], ['cljs.core', 'om.dom', 'defender_cljs.canvas.core', 'om.core']);
goog.addDependency("../cljs/core/async/impl/protocols.js", ['cljs.core.async.impl.protocols'], ['cljs.core']);
goog.addDependency("../cljs/core/async/impl/buffers.js", ['cljs.core.async.impl.buffers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/dispatch.js", ['cljs.core.async.impl.dispatch'], ['cljs.core', 'cljs.core.async.impl.buffers', 'goog.async.nextTick']);
goog.addDependency("../cljs/core/async/impl/channels.js", ['cljs.core.async.impl.channels'], ['cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.buffers', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/ioc_helpers.js", ['cljs.core.async.impl.ioc_helpers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/timers.js", ['cljs.core.async.impl.timers'], ['cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async.js", ['cljs.core.async'], ['cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.buffers', 'cljs.core.async.impl.protocols', 'cljs.core.async.impl.ioc_helpers', 'cljs.core.async.impl.timers']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../figwheel/client.js", ['figwheel.client'], ['goog.net.jsloader', 'cljs.core', 'cljs.core.async', 'clojure.string', 'cljs.reader']);
goog.addDependency("../defender_cljs/dev.js", ['defender_cljs.dev'], ['weasel.repl', 'defender_cljs.core', 'cljs.core', 'cljs.core.async', 'figwheel.client']);
goog.addDependency("../defender_cljs/ai.js", ['defender_cljs.ai'], ['defender_cljs.canvas.system', 'cljs.core', 'defender_cljs.utils', 'defender_cljs.actor']);